INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Help pay for my surgery", "medical", 5000, "2/29/2019", "5/1/2019" );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Shadow IV", "music", 25000, "1/1/18", "1/1/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Help end world hunger", "charity", 100000, "5/1/2019", "12/1/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Deforestation in Costa Rica needs your help", "charity", 200000, "7/1/2019", "3/2/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Animal shelter fundraiser", "charity", 12500, "3/27/2019", "4/5/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Re-make of the original Star Wars", "book", 750000, "2/22/2019", "2/22/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cat needs surgery", "medical", 3700, "3/1/2019", "4/1/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dr. Dre needs your help releasing an album", "music", 13500, "4/1/2019", "11/1/2019");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("World peace", "charity", 1000000, "1/1/2020", "1/1/2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Starcraft V", "book", 88000, "7/4/2019", "7/4/2020");

INSERT INTO users (name, age) VALUES ("Eric", 30);
INSERT INTO users (name, age) VALUES ("Heather", 32);
INSERT INTO users (name, age) VALUES ("Daeha", 28);
INSERT INTO users (name, age) VALUES ("Luis", 24);
INSERT INTO users (name, age) VALUES ("Melissa", 30);
INSERT INTO users (name, age) VALUES ("Joanne", 64);
INSERT INTO users (name, age) VALUES ("Samuel", 57);
INSERT INTO users (name, age) VALUES ("Meghan", 29);
INSERT INTO users (name, age) VALUES ("River", 4);
INSERT INTO users (name, age) VALUES ("Michelle", 34);
INSERT INTO users (name, age) VALUES ("Sherryn", 34);
INSERT INTO users (name, age) VALUES ("Meredith", 35);
INSERT INTO users (name, age) VALUES ("Josh", 37);
INSERT INTO users (name, age) VALUES ("Courtney", 25);
INSERT INTO users (name, age) VALUES ("Kat", 26);
INSERT INTO users (name, age) VALUES ("Avi", 39);
INSERT INTO users (name, age) VALUES ("Ross", 52);
INSERT INTO users (name, age) VALUES ("Rick", 75);
INSERT INTO users (name, age) VALUES ("David", 68);
INSERT INTO users (name, age) VALUES ("Nick", 35);

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 2, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (125, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 19, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2500, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 10, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 13, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 16, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 17, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 9, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (750, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 12, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 9, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 13, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 16, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1250, 8, 7);


